const styles = {
    bg: {
        minHeight: "100vh",
        background: "#f7f8fa",
        padding: "0 0 70px 0",
        position: "relative",
        fontFamily: "Inter, sans-serif",
        maxWidth: "480px",
        margin: "0 auto",
    },
    header: {
        display: "flex",
        alignItems: "center",
        padding: "18px 18px 0 18px",
        background: "#f7f8fa",
    },
    card: {
        background: "#fff",
        borderRadius: 18,
        margin: "18px 18px 0 18px",
        padding: 18,
        boxShadow: "0 2px 8px #0001",
    },
    borrowCard: {
        background: "linear-gradient(90deg,#1e3c72,#2a5298)",
        borderRadius: 18,
        margin: "18px 18px 0 18px",
        padding: 18,
        boxShadow: "0 2px 8px #0001",
    },
    borrowBtn: {
        background: "#fff",
        color: "#1e3c72",
        border: "none",
        borderRadius: 12,
        padding: "8px 22px",
        fontWeight: 700,
        fontSize: 16,
        cursor: "pointer",
        marginTop: 8,
    },
    healthBar: {
        width: "100%",
        height: 8,
        background: "#fff4",
        borderRadius: 6,
        marginTop: 6,
        overflow: "hidden",
    },
    healthBarInner: {
        height: "100%",
        background: "#1ecb81",
        borderRadius: 6,
        transition: "width 0.3s",
    },
    assetCard: {
        background: "#fff",
        borderRadius: 18,
        margin: "18px 18px 0 18px",
        padding: 18,
        boxShadow: "0 2px 8px #0001",
    },
    tabActive: {
        flex: 1,
        background: "#f7f8fa",
        border: "none",
        borderRadius: 12,
        padding: "8px 0",
        fontWeight: 700,
        fontSize: 16,
        color: "#222",
        marginRight: 8,
        cursor: "pointer",
    },
    tab: {
        flex: 1,
        background: "#fff",
        border: "none",
        borderRadius: 12,
        padding: "8px 0",
        fontWeight: 500,
        fontSize: 16,
        color: "#888",
        cursor: "pointer",
    },
    assetRow: {
        display: "flex",
        alignItems: "center",
        padding: "14px 0",
        borderBottom: "1px solid #f0f0f0",
        gap: 14,
    },
    assetIcon: {
        width: 36,
        height: 36,
        marginRight: 14,
    },
    navbar: {
        position: "fixed" as const,
        left: "0",
        right: "0",
        bottom: "0",
        height: "64px",
        background: "#fff",
        borderTop: "1px solid #eee",
        display: "flex",
        alignItems: "center",
        zIndex: 10,
        maxWidth: "480px",
        margin: "0 auto",
    },
    depositBtn: {
        background: "#3b82f6",
        color: "#fff",
        border: "none",
        borderRadius: 12,
        padding: "10px 32px",
        fontWeight: 700,
        fontSize: 16,
        cursor: "pointer",
        marginTop: 18,
        marginBottom: 0,
        width: "100%",
        boxShadow: "0 2px 8px #3b82f622",
    },
    repayBtn: {
        background: "#1ecb81",
        color: "#fff",
        border: "none",
        borderRadius: 8,
        padding: "6px 18px",
        fontWeight: 600,
        fontSize: 14,
        cursor: "pointer",
        marginTop: 8,
    },
    taskCard: {
        background: "#fff",
        borderRadius: 18,
        margin: "24px 18px 0 18px",
        padding: 24,
        boxShadow: "0 2px 8px #0001",
        minHeight: 320,
        textAlign: 'left' as const,
        maxWidth: '480px',
    },
    taskItem: {
        fontSize: 17,
        color: '#222',
        background: '#f7f8fa',
        borderRadius: 10,
        padding: '12px 16px',
        marginBottom: 12,
        display: 'flex',
        alignItems: 'center',
    },
    checkinBtn: {
        background: "#1ecb81",
        color: "#fff",
        border: "none",
        borderRadius: 8,
        padding: "8px 22px",
        fontWeight: 700,
        fontSize: 15,
        cursor: "pointer",
        marginLeft: 12,
    },
    leaderItem: {
        fontSize: 15,
        color: '#222',
        background: '#f7f8fa',
        borderRadius: 8,
        padding: '8px 12px',
        marginBottom: 6,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    ratesCard: {
        background: "#fff",
        borderRadius: 18,
        margin: "24px 18px 0 18px",
        padding: 24,
        boxShadow: "0 2px 8px #0001",
        minHeight: 320,
        textAlign: 'left' as const,
        maxWidth: '480px',
    },
    poolTab: {
        background: '#f7f8fa',
        border: 'none',
        borderRadius: 16,
        padding: '8px 22px',
        fontWeight: 700,
        fontSize: 16,
        color: '#888',
        cursor: 'pointer',
    },
    poolTabActive: {
        background: '#fff',
        color: '#222',
        boxShadow: '0 2px 8px #0001',
    },
    overviewBox: {
        background: '#f7f8fa',
        borderRadius: 16,
        padding: '16px 22px',
        flex: 1,
        textAlign: 'center' as const,
    },
    marketRow: {
        display: 'flex',
        alignItems: 'center',
        background: '#f7f8fa',
        borderRadius: 16,
        padding: '16px 8px',
        marginBottom: 14,
        fontSize: 16,
    },
    menuCard: {
        background: "#fff",
        borderRadius: 18,
        margin: "24px 18px 0 18px",
        padding: 24,
        boxShadow: "0 2px 8px #0001",
        minHeight: 320,
        textAlign: 'left' as const,
        maxWidth: '480px',
    },
    menuBtn: {
        background: '#f7f8fa',
        border: 'none',
        borderRadius: 12,
        padding: '10px 28px',
        fontWeight: 600,
        fontSize: 16,
        color: '#888',
        cursor: 'pointer',
        transition: 'all 0.2s',
    },
    menuBtnActive: {
        background: '#3b82f6',
        color: '#fff',
        fontWeight: 700,
        boxShadow: '0 2px 8px #3b82f622',
    },
    menuLink: {
        color: '#3b82f6',
        fontWeight: 600,
        fontSize: 15,
        textDecoration: 'none',
        transition: 'color 0.2s',
    },
    supportBtn: {
        display: 'inline-block',
        background: '#f7f8fa',
        color: '#222',
        borderRadius: 10,
        padding: '10px 22px',
        fontWeight: 700,
        fontSize: 16,
        textDecoration: 'none',
        marginTop: 6,
        boxShadow: '0 2px 8px #0001',
        transition: 'background 0.2s',
    },
};

export default styles;